### ISSUE TITLE
Polars Series not supported in Matplotlib plot

### ISSUE THREAD

**Issue by RDWimmers** [cemsbv/pygef#157]
From Polars version 0.12 it's not possible to do the following:

```
plt.plot(pl.DataFrame["x"], pl.DataFrame["y"])
```
This creates a `NotImplementedError`

Suggest the following:
```
plt.plot(pl.DataFrame["x"].to_numpy(), pl.DataFrame["y"].to_numpy())
```
One of the lines to change >
https://github.com/cemsbv/pygef/blob/master/pygef/plot_utils.py#L88

**Comment by tversteeg** [comment]
The same issue can be seen in #156.

**Comment by ritchie46** [comment]
Any idea what makes a Series usable in matplotlib? Could add that conversion methods upstream

**Comment by tversteeg** [comment]
> Any idea what makes a Series usable in matplotlib? Could add that conversion methods upstream

The most common type seems to be just 1D arrays: https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot.html#matplotlib.pyplot.plot

**Comment by ritchie46** [comment]
I mean, what operations does matplotlib call to convert to an array.

**Comment by tversteeg** [comment]
I have no idea, their API is very convoluted.
