### ISSUE TITLE
Robertson classification and pandas

### ISSUE THREAD

**Issue by mariosgeo** [cemsbv/pygef#248]
In pandas 1.4.3, when I classify a CPT, i get an error 
'DataFrame' object does not support 'Series' assignment by index. Use 'DataFrame.with_columns'

**Comment by mariosgeo** [comment]
This happens on the utils.py, line 95. I can manually add the 
df=df.to_pandas() and then the codes goes on. Yet, it crashes later on, on the function new_roberston in the line 
.pipe(geo.water_pressure, water_level)

**Comment by breinbaas** [comment]
This looks like a bug due to a change in the underlying polars package

**Comment by ritchie46** [comment]
No it is is a bug in pygef where code did not adhere to latest changes in polars. I recommend using an earlier version of pygef if you need that functionality. 

We are working toward a new version that does not include robertson classifcation.

**Comment by mariosgeo** [comment]
Thanks. I rolled to previous version of polars and it is working/ So no pandas issue I assume.
