### ISSUE TITLE
GEF with single line data, can't be read

### ISSUE THREAD

**Issue by mariosgeo** [cemsbv/pygef#285]
Hi, 
I have several boreholes gef files and in all gef where the description has a single line (see the attached file below) the code returns 

    self._df = PyDataFrame.read_csv(

RuntimeError: Any(NoData("empty csv"))

Can you support this? Below the gef file I am referring to

#GEFID= 1, 1, 0
#FILEOWNER= DataWS
#FILEDATE= 2022, 12, 22
#PROJECTID= Lob van Gennep, 2102701 HB, -
#COLUMN= 2
#COLUMNINFO= 1, m, Laag van, 1
#COLUMNINFO= 2, m, Laag tot, 2
#COMPANYID= -, -, 31
#DATAFORMAT= ASCII
#COLUMNSEPARATOR= ;
#COLUMNTEXT= 1
#LASTSCAN= 1
#XYID= 31000, 196276.20, 412672.60, 0.01, 0.01
#ZID= 31000, 13.22, 0.01
#MEASUREMENTCODE= NEN5104, 1, 0, 0, NNI 1989
#MEASUREMENTTEXT= 3, -, plaatsnaam boring
#MEASUREMENTTEXT= 5, 2022-03-02, datum boorbeschrijving
#MEASUREMENTTEXT= 6, Tla, beschrijver lagen
#MEASUREMENTTEXT= 7, 31000, locaal coördinatiesysteem
#MEASUREMENTTEXT= 8, 31000, locaal referentiesysteem
#MEASUREMENTTEXT= 9, maaiveld, vast horizontaal niveau
#MEASUREMENTTEXT= 13, -, boorbedrijf
#MEASUREMENTTEXT= 14, Nee, openbaar
#MEASUREMENTTEXT= 16, 2022-03-02, datum boring
#MEASUREMENTTEXT= 18, Nee, Peilbuis aanwezig
#MEASUREMENTTEXT= 23, Tla, naam boormeester
#MEASUREMENTTEXT= 31, EDM, boormethode1
#MEASUREMENTVAR= 16, 2.500000, m, eind diepte boring
#MEASUREMENTVAR= 31, 2.500000, m, diepte onderkant boortraject1
#SPECIMENTEXT= 11, 1, monstercode monster1
#SPECIMENTEXT= 12, 2022-03-02, datum monster1
#SPECIMENTEXT= 13, 13:18:29, tijd monster1
#SPECIMENTEXT= 14, G, (on)geroerd monster1
#SPECIMENTEXT= 18, 2, monstercode monster2
#SPECIMENTEXT= 19, 2022-03-02, datum monster2
#SPECIMENTEXT= 20, 13:18:29, tijd monster2
#SPECIMENTEXT= 21, G, (on)geroerd monster2
#SPECIMENTEXT= 25, 3, monstercode monster3
#SPECIMENTEXT= 26, 2022-03-02, datum monster3
#SPECIMENTEXT= 27, 13:18:29, tijd monster3
#SPECIMENTEXT= 28, G, (on)geroerd monster3
#SPECIMENVAR= 1, 3.000000, -, aantal monsters
#SPECIMENVAR= 12, 1.000000, m, onderkant monster1
#SPECIMENVAR= 18, 1.000000, m, bovenkant monster2
#SPECIMENVAR= 19, 2.000000, m, onderkant monster2
#SPECIMENVAR= 25, 2.000000, m, bovenkant monster3
#SPECIMENVAR= 26, 2.500000, m, onderkant monster3
#PROCEDURECODE= GEF-BORE-Report, 1, 0, 0, -
#TESTID= 183.HB4
#REPORTCODE= GEF-BORE-Report, 1, 0, 0, -
#RECORDSEPARATOR= !
#OS= DOS
#LANGUAGE= NL
#EOH=
0.0000e+000;2.5000e+000;'Kz3';;'DO BR';;'KHRD';!

**Comment by tversteeg** [comment]
Thanks for the bug report! It looks like the record separator isn't properly parsed.

**Comment by mariosgeo** [comment]
I think 0.7.4
I have several gef files from the same data source, but the other ones that have more than one line are readable.

I will do some testing to confirm.

**Comment by mariosgeo** [comment]
An update, if I add an extra line in the end of the gef file (see below), then it works

2.5000e+000;2.6000e+000;'Kz3';;'DO BR';;'KHRD';!

**Comment by tversteeg** [comment]
Do you also have this issue with the latest alpha version? On pypi it's [0.8.0a1](https://pypi.org/project/pygef/0.8.0a1/). Your code will need to change a bit for that though.

**Comment by RDWimmers** [comment]
Tested it on the master branch with no errors:

```
>>> import pygef

>>> pygef.read_bore("./285.gef")
Out[3]: 
BoreData(bro_id=None, research_report_date=None, description_procedure='unknown', delivered_location=Location(srs_name='urn:ogc:def:crs:EPSG::28992', x=196276.2, y=412672.6), groundwater_level=None, standardized_location=None, delivered_vertical_position_offset=13.22, delivered_vertical_position_datum='unknown', delivered_vertical_position_reference_point='unknown', bore_rock_reached=None, final_bore_depth=None, final_sample_depth=None, bore_hole_completed=None, data=shape: (1, 8)
┌────────────┬────────────┬────────────┬───────┬────────────┬────────────┬────────────┬────────────┐
│ upperBound ┆ lowerBound ┆ geotechnic ┆ remar ┆ geotechnic ┆ upperBound ┆ lowerBound ┆ soilDistri │
│ ary        ┆ ary        ┆ alSoilCode ┆ ks    ┆ alSoilName ┆ aryOffset  ┆ aryOffset  ┆ bution     │
│ ---        ┆ ---        ┆ ---        ┆ ---   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ f64        ┆ f64        ┆ str        ┆ str   ┆ str        ┆ f64        ┆ f64        ┆ list[f64]  │
╞════════════╪════════════╪════════════╪═══════╪════════════╪════════════╪════════════╪════════════╡
│ 0.0        ┆ 2.5        ┆ Kz3        ┆ 1)    ┆ sterkZandi ┆ 13.22      ┆ 10.72      ┆ [0.0, 0.0, │
│            ┆            ┆            ┆ dark  ┆ geKlei     ┆            ┆            ┆ ... 0.0]   │
│            ┆            ┆            ┆ brown ┆            ┆            ┆            ┆            │
│            ┆            ┆            ┆ 2)    ┆            ┆            ┆            ┆            │
│            ┆            ┆            ┆ klei  ┆            ┆            ┆            ┆            │
│            ┆            ┆            ┆ hard  ┆            ┆            ┆            ┆            │
└────────────┴────────────┴────────────┴───────┴────────────┴────────────┴────────────┴────────────┘, alias='183.HB4')
```
