### ISSUE TITLE
read_cpt should return dedicated exception if file is not gef or xml

### ISSUE THREAD

**Issue by tlukkezen** [cemsbv/pygef#292]
If the user provides a file to `read_cpt` that is neither in the correct .gef or .xml format, pygef tries to read as an xml and throws confusing exceptions.

Specifically, if a user provides a .gef file with erroneous format, the user gets BroXMLParser exceptions, which makes no sense.

**Expected result**
The user should get an insightful exception (e.g. custom UnknownFileFormatException) that explains that the provided file cannot be parsed as a .gef or .xml

**Comment by tversteeg** [comment]
What about files that have wrong file extensions but are otherwise correct, such as `example.gef.bak`?

Maybe another option is to pass an optional flag specifying the type:

```python
read_cpt("example.gef.bak", file_format = FileFormat.GEF)
```
