### ISSUE TITLE
Missing dependency 'typing_extensions'

### ISSUE THREAD

**Issue by rubenjonk** [cemsbv/pygef#320]
Module `typing_extensions` not found. This problem occured on line 8 from `pygef/shim.py`. 

Error was solved by adding `typing-extensions>=4.5.0` to my own requirements. Is it possible to add this to the dependency list of pygef?

**Comment by tversteeg** [comment]
This line is already included in `requirements.txt`, how did you install the package? Maybe it needs to be added to `pyproject.toml` as well.

**Comment by rubenjonk** [comment]
I installed the package in a docker in a dockerfile using `RUN python3 -m pip install -r requirements.txt`. In the requirements `pygef>=0.8.0` is specified.

**Comment by RDWimmers** [comment]
Thanks for creating an issue. `polars` dropped the dependency. We set a strict range with 3574fd2224aeb718486d5523d561fe88f7928938. @tversteeg can you release a new version of `pygef` that has the correct dependency ranges. This should fix this issue, can you confirm @rubenjonk. For supporting higher versions of `polars` we should add `typing_extensions` to our dependencies.
